### ISSUE TITLE
Trouble with using your codebase for another language dataset for exampe timit 

### ISSUE THREAD

**Issue by guemDen** [fordDeepDSP/deepSpeech#18]
Hi Lakshmi,

your project helps me a lot to figure out how to do multi gpu training with data parallelism. I have tested your project with the librispeech dataset and it works fine. But now i got trouble to use your project with another data like timit dataset. Timit is a dataset for phoneme recognition. The training of the model goes straightforward but when i do the testing parallel it doesnt predicts anyting. Ok, for the first epochs that is normal because the net is just learning but for the later epochs it makes not sense. I am searching the error now for 5 days and i dont get it. Do i have forgot something important? Maybe that your project do not support phoneme recognition? 
I also have understood the sequence bucketing with tfrecords and the queuing, but you write in the comments 

```
def _generate_feats_and_label_batch(filename_queue, batch_size):
    """Construct a queued batch of spectral features and transcriptions.

    Args:
      filename_queue: queue of filenames to read data from.
      batch_size: Number of utterances per batch.

    Returns:
      feats: mfccs. 4D tensor of [batch_size, height, width, 3] size.
      labels: transcripts. List of length batch_size.
      seq_lens: Sequence Lengths. List of length batch_size.
    """
```
for this function it returns a 4D tensor but i thought my mfccs got only 3 dimensions. Ok, in the cnn part you add a extra dimension on the mfccs for feeding it into a cnn layer after that on the cnn output you are reshaping it to 3 dimensions for the lstm input. But why are there 4 dimensional mfccs in the tfrecords? 

Greetings Deniz
